#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/q/qhassan/5TeV/CMSSW_8_0_8_patch1/src/TopLJets2015/TopAnalysis/scripts/wrapLocalAnalysisRun.sh "python /afs/cern.ch/work/q/qhassan/5TeV/CMSSW_8_0_8_patch1/src/TopLJets2015/TopAnalysis/scripts/runLocalAnalysis.py -i root://eoscms//eos/cms//store/cmst3/group/hintt/psilva/PP5TeV/data/HighPtLowerPhotons/crab_HighPtLowerPhotons/160823_154451/0000/HiForestAOD_560.root -o /afs/cern.ch/user/q/qhassan/workQhassan/5TeV/CMSSW_8_0_8_patch1/src/TopLJets2015/TopAnalysis/analysis_e/FilteredSingleEleHighPt_v3.root/HiForestAOD_560.root_0.root --charge 0 --ch 11 --era /afs/cern.ch/work/q/qhassan/5TeV/CMSSW_8_0_8_patch1/src/TopLJets2015/TopAnalysis/data/era5TeV --tag HiForestAOD_560.root --flav 0 --method Run5TeVAnalysis::Run5TeVAnalysis"'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
